# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de84dc474ca539af2980315a4d17be18dc3f337fcc9c29247f7cd0bbc0e64be21b2bb47e89176698e3ca81507222ed8db6f07b54d1a505198a42577a744a994e

test:
  secret_key_base: d966b2e7841af17f9be49695e1b8a2d6cc081136d3ac3a86f8cc6361086e5551c011f38d4f7c3f5b2eee270049ac6961b320c42ef836569e8af70e906d634f29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
